name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4 # lee la versión de "packageManager"

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Type-check
        run: pnpm type-check

      - name: Tests
        run: pnpm test
